// lib/fallback-categories.ts
import { Category } from '@/types';

export const fallbackCategories: Category[] = [
  { 
    id: 1, 
    name: 'Electronics', 
    slug: 'electronics', 
    description: 'Devices and gadgets',
    sortOrder: 0,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  { 
    id: 2, 
    name: 'Clothing', 
    slug: 'clothing', 
    description: 'Fashion and apparel',
    sortOrder: 0,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  { 
    id: 3, 
    name: 'Books', 
    slug: 'books', 
    description: 'Books and literature',
    sortOrder: 0,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  { 
    id: 4, 
    name: 'Home & Garden', 
    slug: 'home-garden', 
    description: 'Home improvement and gardening',
    sortOrder: 0,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  { 
    id: 5, 
    name: 'Toys & Games', 
    slug: 'toys-games', 
    description: 'Fun for all ages',
    sortOrder: 0,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  { 
    id: 6, 
    name: 'Sports & Outdoors', 
    slug: 'sports-outdoors', 
    description: 'Fitness and outdoor gear',
    sortOrder: 0,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];